name: Android Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-universal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Universal APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Rename Universal APK
      run: |
        cd app/build/outputs/apk/release
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION_TAG=${GITHUB_REF#refs/tags/}
        else
          VERSION_TAG="dev-${GITHUB_SHA:0:7}"
        fi
        BUILD_NUMBER=${GITHUB_RUN_NUMBER}
        TIMESTAMP=$(date +"%Y%m%d_%H%M")
        for file in *.apk; do
          mv "$file" "OplusAODManager_${VERSION_TAG}_universal_release_${BUILD_NUMBER}_${TIMESTAMP}.apk"
        done
        
    - name: Upload Universal APK
      uses: actions/upload-artifact@v4
      with:
        name: OplusAODManager-universal-release
        path: app/build/outputs/apk/release/OplusAODManager_*_universal_release_*.apk
        
  create-release:
    needs: [build-universal]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Universal APK artifact
      uses: actions/download-artifact@v4
      with:
        name: OplusAODManager-universal-release
        path: apks
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          apks/*.apk
        generate_release_notes: true
        name: ${{ github.ref_name }}
        body: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}